function format(path::String)
    return JuliaFormatter.format(
        path,
        style = nothing;
        throw_on_error = false,
        format_markdown = nothing,
        ignore = nothing,
        overwrite = nothing,
        verbose = true,
        # formatting_options
        # align_assignment = false,
        # align_conditional = false,
        # align_matrix = false,
        # align_pair_arrow = false,
        # align_struct_field = false,
        always_for_in = true,
        always_use_return = true,
        annotate_untyped_fields_with_any = true,
        conditional_to_if = false,
        # disallow_single_arg_nesting = false,
        # enforce_triplequoted_docstrings = true,
        # for_in_replacement = "in",
        # force_long_function_def = false,
        format_docstrings = true,
        import_to_using = false,
        indent = 4,
        # indent_binary_continuations = false,
        indent_submodule = false,
        join_lines_based_on_source = true,
        long_to_short_function_def = false,
        margin = 120,
        # max_iterations = 1,
        normalize_line_endings = "auto",
        pipe_to_function_call = false,
        remove_extra_newlines = true,
        separate_kwargs_with_semicolon = false,
        # short_circuit_to_if = false,
        short_to_long_function_def = false,
        surround_whereop_typeparameters = true,
        trailing_comma = true,
        # trailing_zero = true,
        # transform_syntax_in_macros = false,
        # v2_stable_multiline_strings = false,
        # variable_call_indent = [],
        whitespace_in_kwargs = true,
        whitespace_ops_in_indices = false,
        whitespace_typedefs = true,
        # yas_style_nesting = false,
    )
end