name: CI
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  format:
    name: Format
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v7
      - uses: psrenergy/setup-julia@v1
      - run: julia --project=format format/format.jl

  test-linux:
    name: Test Linux
    runs-on: [self-hosted, linux]
    strategy:
      fail-fast: true
      matrix:
        version:
          - "1.10"
          - "1.11"
          - "1.12"
    steps:
      - uses: actions/checkout@v7
      - uses: psrenergy/setup-git-token@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
        with:
          git_cli: true
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v7
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}